{
 "title": "Kubernetes Cluster Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "query": "label_values(cluster)" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",cluster=~\"^$Cluster$\"}) / sum (machine_memory_bytes{cluster=~\"^$Cluster$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Used Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",cluster=~\"^$Cluster$\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=\"/\",cluster=~\"^$Cluster$\"}[1m]))/ sum (machine_cpu_cores{cluster=~\"^$Cluster$\"}) * 100",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Cluster Used CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",cluster=~\"^$Cluster$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cluster Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{cluster=~\"^$Cluster$\"})"
    }
   ]
  },
  {
   "title": "Cluster Total CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{cluster=~\"^$Cluster$\"})"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",cluster=~\"^$Cluster$\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"^$Cluster$\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}