{
 "title": "Managed Kafka",
 "tags": [
  " Cloud Monitoring",
  "Kafka",
  "GCP"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Broker Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (broker_index)(avg_over_time(managedkafka_googleapis_com:memory_usage{monitored_resource=\"managedkafka.googleapis.com/Cluster\"}[${__interval}]))",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.type",
       "=",
       "managedkafka.googleapis.com/memory/usage"
      ],
      "groupBys": [ "metric.label.broker_index" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$cluster",
      "view": "FULL"
     }
    },
    {
     "promQLQuery": {
      "expr": "sum by (broker_index)(avg_over_time(managedkafka_googleapis_com:memory_limit{monitored_resource=\"managedkafka.googleapis.com/Cluster\"}[${__interval}]))",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.type",
       "=",
       "managedkafka.googleapis.com/memory/limit"
      ],
      "groupBys": [ "metric.label.broker_index" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$cluster",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "flops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (broker_index)(rate(managedkafka_googleapis_com:cpu_core_usage_time{monitored_resource=\"managedkafka.googleapis.com/Cluster\"}[${__interval}]))\n\n\n\n\n",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.type",
       "=",
       "managedkafka.googleapis.com/cpu/core_usage_time"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "$cluster",
      "view": "FULL"
     }
    },
    {
     "promQLQuery": {
      "expr": "sum by (broker_index) (\n  managedkafka_googleapis_com:cpu_limit{monitored_resource=\"managedkafka.googleapis.com/Cluster\"} \n)\n",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.type",
       "=",
       "managedkafka.googleapis.com/cpu/limit"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$cluster",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Request Count Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (broker_index, request) (rate(managedkafka_googleapis_com:request_count{monitored_resource=\"managedkafka.googleapis.com/Cluster\"}[$__interval]))\n",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.type",
       "=",
       "managedkafka.googleapis.com/cpu/core_usage_time"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "$cluster",
      "view": "FULL"
     }
    }
   ]
  },
  { "title": "Cluster Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum(managedkafka_googleapis_com:offline_partitions{monitored_resource=\"managedkafka.googleapis.com/Cluster\"})\n",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "$cluster",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Total Partitions Per Broker",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (broker_index)(managedkafka_googleapis_com:partitions{monitored_resource=\"managedkafka.googleapis.com/Cluster\"})",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "$cluster",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Long-Term Storage Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "avg_over_time(managedkafka_googleapis_com:storage_long_term_usage{monitored_resource=\"managedkafka.googleapis.com/Cluster\"}[$__interval])",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "$cluster",
      "view": "FULL"
     }
    }
   ]
  },
  { "title": "Traffic & Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Byte In Per Topic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (topic_id) (\n  rate(managedkafka_googleapis_com:byte_in_count{\n    monitored_resource=\"managedkafka.googleapis.com/Topic\"\n  }[$__interval])\n)\n",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Byte out Per Topic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (topic_id) (\n  rate(managedkafka_googleapis_com:byte_out_count{\n    monitored_resource=\"managedkafka.googleapis.com/Topic\"\n  }[$__interval])\n)\n",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Topic Request Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (topic_id) (\n  rate(managedkafka_googleapis_com:topic_request_count{\n    monitored_resource=\"managedkafka.googleapis.com/Topic\"\n  }[$__interval])\n)\n",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Topic Error Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (topic_id) (\n  rate(managedkafka_googleapis_com:topic_error_count{\n    monitored_resource=\"managedkafka.googleapis.com/Topic\"\n  }[$__interval])\n)\n",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Messages Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (topic_id) (\n  rate(managedkafka_googleapis_com:message_in_count{\n    monitored_resource=\"managedkafka.googleapis.com/Topic\"\n  }[$__interval])\n)\n",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Request Latency Per Broker (P50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (broker_index, request) (\n  managedkafka_googleapis_com:request_latencies{\n    monitored_resource=\"managedkafka.googleapis.com/Cluster\",\n    percentile=\"50\",\n    request=~\"Produce|FetchConsumer\"\n  }\n)",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Request Latency Per Broker (P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (broker_index, request) (\n  managedkafka_googleapis_com:request_latencies{\n    monitored_resource=\"managedkafka.googleapis.com/Cluster\",\n    percentile=\"99\",\n    request=~\"Produce|FetchConsumer\"\n  }\n)",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Request Latency Per Broker (P999)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (broker_index, request) (\n  managedkafka_googleapis_com:request_latencies{\n    monitored_resource=\"managedkafka.googleapis.com/Cluster\",\n    percentile=\"50\",\n    request=~\"Produce|FetchConsumer\"\n  }\n)",
      "projectName": "$cluster",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "",
      "view": "FULL"
     }
    }
   ]
  },
  { "title": "Consumer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Consumer Lag Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 54 },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (topic_id, broker_index, partition_index) (\n  avg_over_time(managedkafka_googleapis_com:consumer_lag{\n    monitored_resource=\"managedkafka.googleapis.com/TopicPartition\"\n  }[$__interval])\n) > 0\n",
      "projectName": "$cluster",
      "step": "1m"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Stable Consumer Groups Per Broker",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (broker_index) (managedkafka_googleapis_com:consumer_groups{monitored_resource=\"managedkafka.googleapis.com/Cluster\", state=\"Stable\"})\n",
      "projectName": "$cluster",
      "step": "1m"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Rebalancing Consumer Groups Per Broker",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (broker_index) (managedkafka_googleapis_com:consumer_groups{monitored_resource=\"managedkafka.googleapis.com/Cluster\", state=\"PreparingRebalance\"})",
      "projectName": "$cluster",
      "step": "1m"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Dead Consumer Groups Per Broker",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (broker_index) (managedkafka_googleapis_com:consumer_groups{monitored_resource=\"managedkafka.googleapis.com/Cluster\", state=\"Dead\"})\n",
      "projectName": "$cluster",
      "step": "1m"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Empty Consumer Groups Per Broker",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (broker_index) (managedkafka_googleapis_com:consumer_groups{monitored_resource=\"managedkafka.googleapis.com/Cluster\", state=\"Empty\"})\n",
      "projectName": "$cluster",
      "step": "1m"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "",
      "view": "FULL"
     }
    }
   ]
  }
 ]
}