platforms:
  - type: GKE
    detections:
      - characteristic_metric:
          metric_type: prometheus.googleapis.com/redis_uptime_in_seconds/gauge
    launch_stage: GA
    exporter_metadata:
      name: Redis Prometheus Exporter
      doc_url: https://github.com/oliver006/redis_exporter
      minimum_supported_version: v1.43.1
    default_metrics:
      - name: prometheus.googleapis.com/redis_commands_total/counter
        prometheus_name: redis_commands_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_connected_clients/gauge
        prometheus_name: redis_connected_clients
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_db_keys/gauge
        prometheus_name: redis_db_keys
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_memory_used_bytes/gauge
        prometheus_name: redis_memory_used_bytes
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_net_output_bytes_total/counter
        prometheus_name: redis_net_output_bytes_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_net_input_bytes_total/counter
        prometheus_name: redis_net_input_bytes_total
        kind: CUMULATIVE
        value_type: DOUBLE
    install_documentation_url: https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/redis
