platforms:
  - type: GKE
    detections:
      - characteristic_metric:
          metric_type: prometheus.googleapis.com/redis_uptime_in_seconds/gauge
    launch_stage: GA
    exporter_metadata:
      name: Redis Prometheus Exporter
      doc_url: https://github.com/oliver006/redis_exporter
      minimum_supported_version: v1.43.1
    default_metrics:
      - name: prometheus.googleapis.com/redis_commands_total/counter
        prometheus_name: redis_commands_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_connected_clients/gauge
        prometheus_name: redis_connected_clients
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_db_keys/gauge
        prometheus_name: redis_db_keys
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_memory_used_bytes/gauge
        prometheus_name: redis_memory_used_bytes
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_net_output_bytes_total/counter
        prometheus_name: redis_net_output_bytes_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_net_input_bytes_total/counter
        prometheus_name: redis_net_input_bytes_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_latency_percentiles_usec/summary:counter
        prometheus_name: redis_latency_percentiles_usec
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_keyspace_hits_total/counter
        prometheus_name: redis_keyspace_hits_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_keyspace_misses_total/counter
        prometheus_name: redis_keyspace_misses_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_blocked_clients/gauge
        prometheus_name: redis_blocked_clients
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_client_recent_max_input_buffer_bytes/gauge
        prometheus_name: redis_client_recent_max_input_buffer_bytes
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_mem_fragmentation_ratio/gauge
        prometheus_name: redis_mem_fragmentation_ratio
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_slowlog_length/gauge
        prometheus_name: redis_slowlog_length
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/redis_evicted_keys_total/counter
        prometheus_name: redis_evicted_keys_total
        kind: CUMULATIVE
        value_type: DOUBLE
    install_documentation_url: https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/redis
