platforms:
  - type: GKE
    detections:
      - characteristic_metric:
          metric_type: prometheus.googleapis.com/kafka_brokers/gauge
    launch_stage: GA
    exporter_metadata:
      name: Kafka Prometheus Exporter
      doc_url: https://github.com/danielqsj/kafka_exporter
      minimum_supported_version: v1.6.0
    default_metrics:
      - name: prometheus.googleapis.com/kafka_topic_partitions/gauge
        prometheus_name: kafka_topic_partitions
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/kafka_brokers/gauge
        prometheus_name: kafka_brokers
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/kafka_topic_partition_leader/gauge
        prometheus_name: kafka_topic_partition_leader
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/kafka_topic_partition_leader_is_preferred/gauge
        prometheus_name: kafka_topic_partition_leader_is_preferred
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/kafka_topic_partition_under_replicated_partition/gauge
        prometheus_name: kafka_topic_partition_under_replicated_partition
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/kafka_topic_partition_replicas/gauge
        prometheus_name: kafka_topic_partition_replicas
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/kafka_topic_partition_in_sync_replica/gauge
        prometheus_name: kafka_topic_partition_in_sync_replica
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/kafka_topic_partition_current_offset/gauge
        prometheus_name: kafka_topic_partition_current_offset
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/kafka_topic_partition_oldest_offset/gauge
        prometheus_name: kafka_topic_partition_oldest_offset
        kind: GAUGE
        value_type: DOUBLE
    install_documentation_url: https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/kafka
