platforms:
  - type: GKE
    launch_stage: GA
    detections:
      - characteristic_metric:
          metric_type: prometheus.googleapis.com/ray_node_cpu_count/gauge
    exporter_metadata:
      name: Ray Prometheus Exporter
      doc_url: https://docs.ray.io/en/latest/ray-observability/reference/system-metrics.html
      minimum_supported_version: v2.40.0
    default_metrics:
      - name: prometheus.googleapis.com/ray_tasks/gauge
        prometheus_name: ray_tasks
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_actors/gauge
        prometheus_name: ray_actors
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_resources/gauge
        prometheus_name: ray_resources
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_object_store_memory/gauge
        prometheus_name: ray_object_store_memory
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_cpu_utilization/gauge
        prometheus_name: ray_node_cpu_utilization
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_cpu_count/gauge
        prometheus_name: ray_node_cpu_count
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_gpus_utilization/gauge
        prometheus_name: ray_node_gpus_utilization
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_gpus_available/gauge
        prometheus_name: ray_node_gpus_available
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_disk_usage/gauge
        prometheus_name: ray_node_disk_usage
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_disk_free/gauge
        prometheus_name: ray_node_disk_free
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_disk_io_write_speed/gauge
        prometheus_name: ray_node_disk_io_write_speed
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_disk_io_read_speed/gauge
        prometheus_name: ray_node_disk_io_read_speed
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_mem_used/gauge
        prometheus_name: ray_node_mem_used
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_mem_total/gauge
        prometheus_name: ray_node_mem_total
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_component_rss_mb/gauge
        prometheus_name: ray_component_rss_mb
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_mem_shared_bytes/gauge
        prometheus_name: ray_node_mem_shared_bytes
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_component_cpu_percentage/gauge
        prometheus_name: ray_component_cpu_percentage
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_gram_used/gauge
        prometheus_name: ray_node_gram_used
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_gram_available/gauge
        prometheus_name: ray_node_gram_available
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_network_receive_speed/gauge
        prometheus_name: ray_node_network_receive_speed
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/ray_node_network_send_speed/gauge
        prometheus_name: ray_node_network_send_speed
        kind: GAUGE
        value_type: DOUBLE
    install_documentation_url: https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/kuberay
