platforms:
  - type: GKE
    detections:
      - characteristic_metric:
          metric_type: prometheus.googleapis.com/envoy_server_live/gauge
    launch_stage: GA
    exporter_metadata:
      name: Istio Prometheus Exporter
      doc_url: https://istio.io/latest/docs/ops/integrations/prometheus
    default_metrics:
      - name: prometheus.googleapis.com/istio_requests_total/counter
        prometheus_name: istio_requests_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/istio_request_duration_milliseconds/histogram
        prometheus_name: istio_request_duration_milliseconds
        kind: CUMULATIVE
        value_type: DISTRIBUTION
      - name: prometheus.googleapis.com/istio_request_bytes/histogram
        prometheus_name: istio_request_bytes
        kind: CUMULATIVE
        value_type: DISTRIBUTION
      - name: prometheus.googleapis.com/istio_response_bytes/histogram
        prometheus_name: istio_response_bytes
        kind: CUMULATIVE
        value_type: DISTRIBUTION
      - name: prometheus.googleapis.com/envoy_server_live/gauge
        prometheus_name: envoy_server_live
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/envoy_server_uptime/gauge
        prometheus_name: envoy_server_uptime
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/envoy_server_memory_allocated/gauge
        prometheus_name: envoy_server_memory_allocated
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/envoy_server_memory_heap_size/gauge
        prometheus_name: envoy_server_memory_heap_size
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/envoy_cluster_membership_healthy/gauge
        prometheus_name: envoy_cluster_membership_healthy
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/envoy_cluster_membership_total/gauge
        prometheus_name: envoy_cluster_membership_total
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/envoy_cluster_upstream_cx_active/gauge
        prometheus_name: envoy_cluster_upstream_cx_active
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/envoy_cluster_upstream_rq_total/counter
        prometheus_name: envoy_cluster_upstream_rq_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/envoy_server_memory_allocated/gauge
        prometheus_name: envoy_server_memory_allocated
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/envoy_cluster_upstream_cx_rx_bytes_total/counter
        prometheus_name: envoy_cluster_upstream_cx_rx_bytes_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/envoy_cluster_manager_cds_update_attempt/counter
        prometheus_name: envoy_cluster_manager_cds_update_attempt
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/envoy_cluster_manager_cds_update_success/counter
        prometheus_name: envoy_cluster_manager_cds_update_success
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/envoy_cluster_manager_cds_update_failure/counter
        prometheus_name: envoy_cluster_manager_cds_update_failure
        kind: CUMULATIVE
        value_type: DOUBLE
    install_documentation_url: https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/istio
