platforms:
  - type: GKE
    detections:
      - characteristic_metric:
          metric_type: prometheus.googleapis.com/haproxy_backend_current_sessions/gauge
    launch_stage: GA
    exporter_metadata:
      name: HAProxy Prometheus Exporter
      doc_url: https://github.com/prometheus/haproxy_exporter
      minimum_supported_version: "2.4"
    default_metrics:
      - name: prometheus.googleapis.com/haproxy_frontend_http_responses_total/counter
        prometheus_name: haproxy_frontend_http_responses_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_backend_http_responses_total/counter
        prometheus_name: haproxy_backend_http_responses_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_frontend_bytes_in_total/counter
        prometheus_name: haproxy_frontend_bytes_in_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_frontend_bytes_out_total/counter
        prometheus_name: haproxy_frontend_bytes_out_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_backend_bytes_in_total/counter
        prometheus_name: haproxy_backend_bytes_in_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_backend_bytes_out_total/counter
        prometheus_name: haproxy_backend_bytes_out_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_backend_connection_errors_total/counter
        prometheus_name: haproxy_backend_connection_errors_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_frontend_connections_total/counter
        prometheus_name: haproxy_frontend_connections_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_frontend_current_sessions/gauge
        prometheus_name: haproxy_frontend_current_sessions
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_backend_current_sessions/gauge
        prometheus_name: haproxy_backend_current_sessions
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_frontend_http_requests_total/counter
        prometheus_name: haproxy_frontend_http_requests_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_frontend_request_errors_total/counter
        prometheus_name: haproxy_frontend_request_errors_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_backend_response_errors_total/counter
        prometheus_name: haproxy_backend_response_errors_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_frontend_requests_denied_total/counter
        prometheus_name: haproxy_frontend_requests_denied_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/haproxy_backend_retry_warnings_total/counter
        prometheus_name: haproxy_backend_retry_warnings_total
        kind: CUMULATIVE
        value_type: DOUBLE
    install_documentation_url: https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/haproxy
